server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/spring_practice3?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: h25189230!
    driver-class-name: com.mysql.cj.jdbc.Driver

